# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'legalBlocks' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for legalBlocks

  target 'legalBlocks-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'legalBlocksTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'legalBlocks-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for legalBlocks-tvOS

  target 'legalBlocks-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
